export var lineChartData = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "Squat",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "#4787ff",
            borderColor: "#4787ff",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: '#4787ff',
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "#4787ff",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 3,
            pointHitRadius: 10,
            data: [225, 275, 285, 315, 315, 315, 355],
            spanGaps: false,
        },
        {
          label: "Bench Press",
          fill: false,
          lineTension: 0.1,
          backgroundColor: "#ffbf47",
          borderColor: "#ffbf47",
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: "#ffbf47",
          pointBackgroundColor: "#fff",
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "#ffbf47",
          pointHoverBorderColor: "rgba(220,220,220,1)",
          pointHoverBorderWidth: 2,
          pointRadius: 3,
          pointHitRadius: 10,
          data: [225, 275, 285, 285, 285, 285, 285],
          spanGaps: false,
        },
        {
          label: "DeadLift",
          fill: false,
          lineTension: 0.1,
          backgroundColor: "rgba(255, 99, 71, 1)",
          borderColor: "rgba(255, 99, 71, 1)",
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: "rgba(255, 99, 71, 1)",
          pointBackgroundColor: "#fff",
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgba(255, 99, 71, 1)",
          pointHoverBorderColor: "rgba(220,220,220,1)",
          pointHoverBorderWidth: 2,
          pointRadius: 3,
          pointHitRadius: 10,
          data: [235, 275, 315, 355, 405, 405, 435],
          spanGaps: false,
        }
        ,
        {
          label: "OH Press",
          fill: false,
          lineTension: 0.1,
          backgroundColor: "#212121",
          borderColor: "#212121",
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: "#212121",
          pointBackgroundColor: "#fff",
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "#212121",
          pointHoverBorderColor: "rgba(220,220,220,1)",
          pointHoverBorderWidth: 2,
          pointRadius: 3,
          pointHitRadius: 10,
          data: [90, 135, 155, 185, 205, 205, 205],
          spanGaps: false,
        }
    ]
};
